### ISSUE TITLE
add new judgement fonts

### ISSUE THREAD

**Issue by ianklatzco** [ddrillini/uiuc-wendy#10]
for sangyeol

[Simply-Love-Judgment-Fonts.zip](https://github.com/ddrillini/uiuc-wendy/files/1672261/Simply-Love-Judgment-Fonts.zip)

**Comment by ianklatzco** [comment]
unfortunately, these'll probably get wiped when i theme update.

i think some theme settings are stored in stepmania and some are stored in the theme folder, because simply love has a lot of features implemented at theme level.

these go in: `Themes/Simply-Love-SM5/Graphics/_judgments`

possible fix: symlink the judgement fonts folder, and then when i theme update, rm that folder before transferring over? a little bit obnoxious.

i think there may be some scripts included on the cab for clean updating.

**Comment by andrewipark** [comment]
I have this problem with groove-fz judge font as well. oh well.
You'd still have to be careful not to remove the symlink out of the folder when you replaced everything.

**Comment by ianklatzco** [comment]
hmmm, if i updated the theme by `git pull`ing then it wouldn't be a problem. I'll do that in the future.
Dan is likely EOL'ing the theme soon, so I don't think it'll be a problem.

**Comment by ianklatzco** [comment]
added
