### ISSUE TITLE
Gate is too quiet

### ISSUE THREAD

**Issue by ianklatzco** [ddrillini/uiuc-wendy#14]
@frumsdotxyz kindly tweaked the audio and made this: [gate.zip](https://github.com/ddrillini/uiuc-wendy/files/1746675/gate.zip)

todo:
- upload to RIP10/
- compare how it sounds to the one already in the pack

**Comment by andrewipark** [comment]
it's hard to tell on my computer. looks like some DR compression was used to amplify by about 3 dB.
Will test on machine tomorrow, hopefully this doesn't have the same issue that China Dress did...

**Comment by andrewipark** [comment]
We're using the updated version
idk if we want to keep both ver or what
