### ISSUE TITLE
openitg/stepmania switcher

### ISSUE THREAD

**Issue by ianklatzco** [ddrillini/uiuc-wendy#2]
problem: 
 * openitg and stepmania are both installed (`~/openitg/openitg` and `~/SM5/stepmania` respectively)
 * i want any member to be able to hit a button code to swap between them so that anyone can play legacy content without my needing to be present to switch

* stepmania starts at boot via a file or line in ~/.config/autostart
* altering this to a script that
     * starts stepmania at boot
     * on the death of stepmania, starts openitg
     * on the death of openitg, re-calls the script
* then writing a button code into each theme to call the `Exit Game` function

would solve the problem.

there's a script in ~/Util/swap-games.sh, but i think i left it in a state that forkbombs the cab.

i'm working on this bit-by-bit, will report progress here.

(once this is done we can load a bunch of 3.95 compatible mods content)

**Comment by ianklatzco** [comment]
the script no longer forkbombs.

there was an audio issue (audio would cut out after a switch) but i resolved it by adding longer delays between closing and opening versions of stepmania.

**Comment by ianklatzco** [comment]
```
#!/bin/bash
(export DISPLAY=:0.0 ;~/SM5/stepmania 2>&1 /dev/null &) &&\
(export DISPLAY=:0.0 ; ~/openitg/openitg 2>&1 /dev/null &) && ~/Util/swap-games.sh
```

**Comment by andrewipark** [comment]
Super late, but requesting upload of your copy of this to the repo @ianklatzco . In all the excitement this summer I forgot to copy this over.

**Comment by ianklatzco** [comment]
what exactly? the above snippet of code?

**Comment by andrewipark** [comment]
`~/Util/swap-games.sh`

**Comment by ianklatzco** [comment]
i no longer have it, but i'm pretty sure it was just those above two lines.

**Comment by ianklatzco** [comment]
Solved with some amazon dash buttons and the amazon-dash pip package.
![photo_2018-09-29_22-27-23](https://user-images.githubusercontent.com/1487413/46253001-539f6300-c437-11e8-817f-af15560bffeb.jpg)
