### ISSUE TITLE
RIP10 theme background glitch

### ISSUE THREAD

**Issue by andrewipark** [ddrillini/uiuc-wendy#23]
steps:
* go into options menu
* go out of options menu
* the background will go to (and stay) white until the song select screen

Ian noticed this

- [x] send a commit to the RIP10 branch of our repo
- [x] copy the repo back over to the machine

**Comment by andrewipark** [comment]
Hard to pin down, but thankfully easy to fix.

In the `BGAnimations/_shared background normal/default.lua`, you have to change _both_ instances of `Color.White` in the def of the main actor frame `af` to the custom color.

**Comment by ianklatzco** [comment]
🙏 🙏 🙏

**Comment by ianklatzco** [comment]
forked simply love theme into ddrillini
https://github.com/ddrillini/Simply-Love-SM5

**Comment by ianklatzco** [comment]
pushed rip10 changes onto a separate branch.
https://github.com/ddrillini/Simply-Love-SM5/tree/rip10

**Comment by ianklatzco** [comment]
https://github.com/ddrillini/Simply-Love-SM5/commit/b78ee7ee77cb8dfe61c016c4c9c5c4b2aa2ebe8d

**Comment by ianklatzco** [comment]
@andrewipark , does that fix it?

**Comment by ianklatzco** [comment]
ok so idk how i actually left the machine's theme state but probably another folder called `Themes/rip10`.

i want the entire git repo ddrillini/Simply-Love-SM5 in there, and then `git checkout rip10`

future updates can be done with an `rsync -vru` to update, since it won't re-copy all the git object files

**Comment by andrewipark** [comment]
Yeah, you currently have the entire theme set up as a different `rip10-theme`. Now switching between the cosmetic versions requires one git command (and shut down SM first, probably).

also `rsync`, bless

**Comment by ianklatzco** [comment]
no need to have multiple issue trackers
