### ISSUE TITLE
update default song and weights to tournament pack

### ISSUE THREAD

**Issue by ianklatzco** [ddrillini/uiuc-wendy#27]
default song:
 - check the name of the pack w/o difficulty prefixes
 - make that `RIP10`
 - make the one w/ difficulty prefixes `RIP10 (prefixes)`
 - reloadsongs

change https://github.com/ddrillini/Simply-Love-SM5/blob/master/Scripts/SL_Init.lua#L341 to `GAMESTATE:SetPreferredSong( SONGMAN:FindSong("RIP10/Airtraveler") )`

in the same file, make the weights as in https://docs.google.com/document/d/15UJxlusI14WfmcbcG90zO6LVbmGkgYilrafTLS2tzVE/edit

**both "percentscoreweight" and "gradeweight" under "competitive"**
```
Fantastic: 5 points
Excellent: 4 points
Great: 3 points
Miss: 0 points
Mines: -2 points
Dropped Holds: 0 points
Holds Kept: 2 points
```

**Comment by andrewipark** [comment]
Done
