### ISSUE TITLE
i want zsh but there's a missed shared library

### ISSUE THREAD

**Issue by ianklatzco** [ddrillini/uiuc-wendy#31]
`zsh`
`zsh: error while loading shared libraries: libtinfo.so.6: cannot open shared object file: No such file or directory`

https://github.com/Valloric/YouCompleteMe/issues/778

**Comment by andrewipark** [comment]
This should probably wait until we discuss the shift to Ubuntu LTS.

**Comment by ianklatzco** [comment]
i agree, fuck it
