### ISSUE TITLE
add valex 9 to both machines

### ISSUE THREAD

**Issue by ianklatzco** [ddrillini/uiuc-wendy#33]
https://twitter.com/jberk16/status/973376862876512256?s=21

**Comment by andrewipark** [comment]
also https://www.dropbox.com/s/a3gwz0pqivxb96j/Crispy%20Liquid.rar?dl=0

**Comment by andrewipark** [comment]
Crispy Liquid not added but oh well

**Comment by andrewipark** [comment]
Didn't see "both machines" in title. Oops.
It's on main cab.

**Comment by andrewipark** [comment]
closed b/c RIP now over
