### ISSUE TITLE
ITG3 noteskins

### ISSUE THREAD

**Issue by sangyeolbaek** [ddrillini/uiuc-wendy#37]
More noteskins, originated from (unofficial) itg3 will be added soon. This includes:

- **Cyber**: resembles the "enchantment" and "charmed" noteskins
- **Shadow**: black body with colored outline
- **Trax**: somewhat resembles a ddr noteskin with LED-like colors
- **Vintage**: looks like the "metal" noteskin with white/black outlines and color flashing like a gauge
- **Vel**: the "more readable metal" noteskin

**Comment by sangyeolbaek** [comment]
just realized I forgot the "cyber" noteskin
here is the file for it
[Cyber.zip](https://github.com/ddrillini/uiuc-wendy/files/1854136/Cyber.zip)

sorry about that!

**Comment by andrewipark** [comment]
"charmed" is just enchantment + some different metrics + a fix to the "up + down arrows drift 1px every other beat

**Comment by andrewipark** [comment]
Added.
