### ISSUE TITLE
buy a locker

### ISSUE THREAD

**Issue by ianklatzco** [ddrillini/uiuc-wendy#40]
dimensions of space next to cab:
39” width
26” depth
83” height
current shelves:
30” w
14” d
38.5” h

**Comment by andrewipark** [comment]
we still need some sort of organizational structure *inside* the locker

**Comment by ianklatzco** [comment]
"horizonal filing cabinet" according to friends @ fab lab

**Comment by ianklatzco** [comment]
current lockers are http://www.krstrikeforce.com/products/linds-upright-locker
looks like there's a supplier in savoy, precision drilling. these look p expensive tho.

let's shoot to do it by the second SORF funding period, or maybe i'll do some research tomorrow.

**Comment by ianklatzco** [comment]
i have set up craigslist saved searches that should email me whenever something comes up. i'll plan a pickup whenever i see something that matches our description.

**Comment by andrewipark** [comment]
What’s the update now that we bought something?

**Comment by ianklatzco** [comment]
* reimburse me (verify it's ok w/ rest of club)
* buy organizer boxes for inside (goodwill, cardbord amazon boxes)
