### ISSUE TITLE
try thread repair kit for fixing brackets

### ISSUE THREAD

**Issue by ianklatzco** [ddrillini/uiuc-wendy#43]
[one](https://trello-attachments.s3.amazonaws.com/59f8a075281fc9540227d4bd/5ad22b342855bccaf8b94405/608b4188d6c239874f04eedb670ded43/image.png)

[two](https://trello-attachments.s3.amazonaws.com/59f8a075281fc9540227d4bd/5ad22b342855bccaf8b94405/e87d82ad03da737a24372fb6c427fe8d/image.png)

**Comment by ianklatzco** [comment]
dave nelson:
```
Apparently thread repair inserts are a thing that exists
This could be used to solve your issue with the L-brackets
So the outer thread is slightly larger than the original hole's size, so it will fit in snugly
And the inner thread is the same size as the original hole, so you can screw the original screws in
They sell repair kits
So it's just a matter of getting the right size.
```

**Comment by andrewipark** [comment]
Please correct me if I'm wrong:
this solves being able to _use_ the L-brackets, which means we need less foam, which means we have to deal with raising the pads less. However, the triangle pieces are still inadequate to solve the problem of holding the brackets into place. So if we did this, could we get away with screws of the proper size thread, but with oversized heads?

**Comment by ianklatzco** [comment]
oversized screwheads is a good idea :pray: thank

**Comment by impman** [comment]
You can either use oversized heads, correctly fitting washers, or just get steel plate and drill holes in it to make new triangle parts.

**Comment by andrewipark** [comment]
Closing, since we have bought parts for this.
