### ISSUE TITLE
simfile updates 2018-06.5

### ISSUE THREAD

**Issue by andrewipark** [ddrillini/uiuc-wendy#47]
- [mute 6](https://www.dropbox.com/s/h86ptrqo8xhfzwu/Mute%20Sims%206%20%5BITG%5D.zip?dl=0)
- [valex 9](https://www.dropbox.com/s/l7oj987kyxr4z9t/Valex%27s%20Magical%204-Arrow%20Adventure%209.zip?dl=0)

nice!

- delete beta version of Skittles 4

**Comment by ianklatzco** [comment]
https://www.dropbox.com/s/s4x5l2cubq8ossp/In%20and%20Out%20of%20Love.zip?dl=0

**Comment by andrewipark** [comment]
done
