### ISSUE TITLE
pack requests / fixes

### ISSUE THREAD

**Issue by feedbacker** [ddrillini/uiuc-wendy#49]
fix:
- there's a new sync update for valex 9. 
src: https://twitter.com/jberk16/status/1009275497572978689

requests:
- The Apocalypse Sampler
- Trails of Cold Stream 2
- Untitled Stream Pack
- Jimmy Jawns 3
- Brule's Brute Beats
- BangerZ (minus "bitch i look like goku")

This would provide more utility than just putting ECS unlocks since it does have lower difficulties, haha.

**Comment by andrewipark** [comment]
I still need to find TAS, USP, JJ3, BBB.
ToCS was a RAR so will have to wait.
updates forthcoming

**Comment by andrewipark** [comment]
All except trails uploaded

**Comment by andrewipark** [comment]
note to self: remove banner from one of the zim songs (sorry, forget which one)

**Comment by feedbacker** [comment]
That would be squid vs pantyhose.

**Comment by ianklatzco** [comment]
pls put in ian5v https://twitter.com/rikameme/status/1018631165228412928?s=21

**Comment by andrewipark** [comment]
Done... finally. Sorry about that.
