### ISSUE TITLE
Upgrade SM to 5.1 and enable USB

### ISSUE THREAD

**Issue by feedbacker** [ddrillini/uiuc-wendy#51]
While I was having breakfast today, I built 5.1 for Ubuntu 16.04 LTS x64.
Let's upgrade to this and enable USB.

(technically, slightly ahead of 5.1b1. It's a compile of latest 5.1 branch)
______
Long read of explanation:

Upgrading to this would supposedly allow loading songs from USB, which would be very beneficial for two reasons:

- Stepchart writers can test their files quicker because they don't have to go through machine admins
- Players don't have to ask machine admins to add multiple packs just to play few songs in the pack.
There are already way too many packs in the machine to navigate through / maintain.

or 

- Players don't have to ask machine admins to add multiple packs when only themselves can virtually play. (ex. me with 18+ footer packs.)

Also,

- even with no USB song loading, we should enable USB, since people can save their records/preferences/screenshots in their USB. 

Saving people from setting their mods every time when they play, that's real nice for sure.

**Comment by ianklatzco** [comment]
is SL supported for 5.1?

**Comment by ianklatzco** [comment]
according to SM5-USBs.pdf (in this repo), usb support is enabled for 5.0.12. When we were running arch, it’d recognize usb sticks, but we couldn’t get it to load custom songs.

**Comment by feedbacker** [comment]
- usb profile support was 5.0.12. usb songs are from 5.1b1. iirc. so, i wouldn't be surprised if it recognized usb sticks, but not load songs.

- SL 4.8 runs well in 5.1. I've loaded it up in my VM and it was aite.
I haven't fully tested it cuz vm framerates are pretty foon (^^). (like 10fps)
but i got through selecting songs and playing songs.

it should be fine. I have faith in dbk2's notes from the release note of 4.8:
"Please note that this requires StepMania 5.0.12 or StepMania 5.1-beta1. Future releases of SM5.1 should also work fine."

and worst comes to just reverting back to the old binary. ezpz.

**Comment by feedbacker** [comment]
So on Windows ver, after you insert a usb drive, play through your round, then it should create a folder called "Stepmania 5.1"

Then, you create a folder inside "Stepmania 5.1" called "Songs" and add the song folders.

I'm sure it would be similar in Linux ver too.
____
That's a little extra step for those coming from ITG r21 era, since it creates "Songs" folder for you.
So, if we do proceed, we should have like a little guide.

Actually, I think we should have video tutorials for navigating the machine and explaining the modern techs in the charts, but that's a lot of investment.

Someday.

**Comment by andrewipark** [comment]
The old setup didn't ever recognize any USBs when I tested, but that's immaterial since we'd have to reproduce the whole mounting thing in the guide (it's somewhere in this repo) anyways.

**Comment by andrewipark** [comment]
We're done!
