### ISSUE TITLE
Forced to play a song without settable mods on stage numbers greater than 4

### ISSUE THREAD

**Issue by ekjellman** [ddrillini/uiuc-wendy#52]
I suspect this is a bug in Simply Love, not anything specific to the UIUC SL machine, but I wanted to mark it down.

I played a game on the SL machine, and somehow full excellent comboed all three songs. I then continued and was forced to play "Sugar Song and Bitter Step" on what seemed like 1.5x reverse with a DDR style noteskin, without being able to access setting.

It seems like I triggered the conditions for an extra stage, but I suspect? that we have extra stage turned off. But continuing allowed the stage number to be above the number of normally allowed songs for a credit.

I don't see any changes in the repository recently that would change this, and I've only spent about 5-10 minutes looking for similar code in the base Simply Love. **I'm mostly reporting this just in case someone made a change that would do that on this machine and not in Simply Love as a whole.**

I did not reproduce. I'm not that good / not bored enough to play a bunch of level 2-3 stuff. Today.

**Comment by ekjellman** [comment]
I was able to reproduce this with feedbacker. We FEC'd "Excitebike (NES) Music - Title Theme" three times, and then continued. Afterwards, we were forced to play "Windows XP Shutdown Sound" wihtout being able to change settings.

feedbacker's theory (and I agree) is that it makes you play the hardest song in that folder as the extra stage. In the case of SOWNDS, Sugar Song and Bitter Step is a 12 (which is hard for that folder). Windows XP Shutdown Sound is a "421"

Again, no idea if this is a UIUC SL machine specific bug, or a SL theme bug in general.

**Comment by ekjellman** [comment]
Further testing indicates that doing well on the last song is sufficient. (We both missed arrows on purpose on the first two songs)

That's enough credits spent on this. ^_^;

**Comment by ianklatzco** [comment]
extra stage is probably enabled in settings. it's a SM thing, but SL has a toggle in the settings. i think it should be disabled, because it's a bit silly.

thank you for finding the source of the issue!

**Comment by andrewipark** [comment]
Wow, thanks for reporting this!

I wasn't aware that SM deferred to SL logic re. extra stages, but I'll report this to upstream SL to make sure that he makes the wording around this setting stronger.

This should be fixed today alongside other machine maintenance tasks.

**Comment by ekjellman** [comment]
Confirmed fixed yesterday.

Wow I hope this doesn't reopen it.
