### ISSUE TITLE
monitor flickering

### ISSUE THREAD

**Issue by andrewipark** [ddrillini/uiuc-wendy#55]
Every so often, the monitor resizes slightly (as if de-skewing?) for 0.5-1 second before returning to normal.
Not a critical issue, but extremely annoying to watch.
Also spotted by @ekjellman ?

**Comment by ianklatzco** [comment]
when? bootup?

**Comment by andrewipark** [comment]
no, this is during gameplay

**Comment by ianklatzco** [comment]
pls film & send me

**Comment by andrewipark** [comment]
I javen't seen this recently and will wait for a few more days to see if it comes back

**Comment by andrewipark** [comment]
Closing because I couldn't reproduce this yesterday.
