### ISSUE TITLE
upload fb3 pack to machine

### ISSUE THREAD

**Issue by ianklatzco** [ddrillini/uiuc-wendy#58]
https://www.dropbox.com/sh/1n3s6z95kqvod4m/AACzNu8f9eWInDvaE4t1lB5Xa?dl=0

**Comment by andrewipark** [comment]
Suggest removing he other two Fantastic Beats packs since both tournaments are over now

**Comment by ianklatzco** [comment]
agree, pls do

**Comment by ianklatzco** [comment]
i'm leaving them because ben needs them for rip10.5

**Comment by ianklatzco** [comment]
ben already did this
