### ISSUE TITLE
Forced to play song without mods when continuing after FEC

### ISSUE THREAD

**Issue by ekjellman** [ddrillini/uiuc-wendy#59]
See https://github.com/ddrillini/uiuc-wendy/issues/52

**Comment by ianklatzco** [comment]
You're welcome to grab the keyboard and modify the setting yourself. Happy to direct you to where it is if you're unsure.

**Comment by ekjellman** [comment]
I'll be back in tomorrow, I can do that if no one else gets to it before me.

I'm not certain how to access the menus while in coin-op mode, but I can probably stumble/google my way through that.

**Comment by ianklatzco** [comment]
Generally mapped to Scroll Lock or Home by default. In our case, it's scroll lock.

**Comment by ekjellman** [comment]
Changed the setting. It seems to work.

While I was in there, I also changed two other settings I think were set before that were not now:
Best scores per player: 10 -> 1
Carry Combo: On -> Off

If I should not have done this, let me know and I can change it back tomorrow.

Closing.

**Comment by ianklatzco** [comment]
lgtm!
