### ISSUE TITLE
New Year's packs

### ISSUE THREAD

**Issue by andrewipark** [ddrillini/uiuc-wendy#6]
I propose adding the following from the most recent releases:

- Banchan - Mandodo's newest minipack
- ~Eurobeat is fantastic (apparently a bit wobbly)~ (mute resync)
- Koreyja
- Holiday Hoedown
- ~Trancemania 3~

Difficulty range should be fine.

To the best of my knowledge, none of these contain objectionable songs.

**Comment by ianklatzco** [comment]
+ [fantastic beats (download link)](https://www.dropbox.com/s/wpe7t08rrgl0syd/Fantastic%20Beats%202.zip?dl=0)

**Comment by ianklatzco** [comment]
added:
* trancemania 3
* fantastic beats 2
* Cirque du Enzo

**Comment by andrewipark** [comment]
Added Eurobeat is Fantastic.

**Comment by andrewipark** [comment]
Done, closing.
