### ISSUE TITLE
plan a night to watch the FP

### ISSUE THREAD

**Issue by ianklatzco** [ddrillini/uiuc-wendy#61]
https://www.youtube.com/watch?v=r5QtZs09_0Y

**Comment by andrewipark** [comment]
This should really be talked about in Discord, not here.

**Comment by ianklatzco** [comment]
discord is short-term low latency ephemeral, here's long-term higher latency and we don't lose track of things.

**Comment by andrewipark** [comment]
bump because someone mentioned it elsewhere

**Comment by andrewipark** [comment]
Bump again b/c we only have a few more weeks this semester!!!!

**Comment by ianklatzco** [comment]
reading day?

**Comment by ianklatzco** [comment]
reading day eve. dumping the FP b/c excessive poor tasteless usage of the N word. i'll check out the second to see if it's any better.
