### ISSUE TITLE
Fix test/service buttons inside machine

### ISSUE THREAD

**Issue by ianklatzco** [ddrillini/uiuc-wendy#62]
machine****

**Comment by andrewipark** [comment]
Did the mappings break again? I got RR staff to fix service sometime in July

**Comment by ianklatzco** [comment]
no, the physical buttons inside are broken.

**Comment by andrewipark** [comment]
Where's the sob github emoji reaction?
And oh. Do we need to contact RR staff to get it open again or can it be done from rear?

**Comment by ianklatzco** [comment]
ask donno for key

**Comment by ianklatzco** [comment]
proposed alternative: dash buttons that serve this same purpose.

problem: it's possible the machine'll get updated and the dash buttons won't be moved over.

**Comment by andrewipark** [comment]
I was told this was done in SU19.
