### ISSUE TITLE
use dash buttons to changing modes. give to rec room staff.

### ISSUE THREAD

**Issue by ianklatzco** [ddrillini/uiuc-wendy#63]
ubuntu has a thing for kb shortcuts

**Comment by andrewipark** [comment]
I don't recommend telling the Rec Room staff to use the keyboard, because StepMania's F3 debug menu is extremely large, and it is easy to accidentally hit something else and cause non-intended effects.

It should be easier to disable SL's Home mode, although I would prefer that some sort of additional toggle is provided to allow UIUC theme testers to still use Home Mode on their personal setups.

**Comment by ianklatzco** [comment]
i doubt uiuc testers will be using our fork, but we COULD encourage that. that's a good idea.

i agree that menu is bad. we should maybe make a keyboard shortcut in ubuntu.

**Comment by andrewipark** [comment]
How would a keyboard shortcut work...? something that auto-fires a script similar to the reload songs script (which is still not back on the machine, last I checked)?

**Comment by ianklatzco** [comment]
no, just map like ctrl h to f3 1

**Comment by ianklatzco** [comment]
or, more SL’s menus to be simpler and expose a “more settings” option

**Comment by andrewipark** [comment]
The first strategy still exposes the issue that they might accidentally leave the machine on home mode

**Comment by ianklatzco** [comment]
i haven't looked at that code recently but i'm pretty sure we could show just the two options

**Comment by andrewipark** [comment]
In the theme prefs row, yes. In the F3 menu, no.

**Comment by ianklatzco** [comment]
probably just gonna map a kb shortcut to F3+1 and tell them to press the kb shortcut until it's in free play

**Comment by ianklatzco** [comment]
todo: buy two amazon dash buttons

**Comment by ianklatzco** [comment]
can someone who is not me do this (ie andrew could you please ask ask a fresh/soon to do this , probably emilia)? you can get them for free.

**Comment by ianklatzco** [comment]
@peterzukerman do you get emailed if i @ you?

**Comment by peterzukerman** [comment]
Nope, only go this from you directly.
