### ISSUE TITLE
logo thread (nice)

### ISSUE THREAD

**Issue by ianklatzco** [ddrillini/uiuc-wendy#69]
@impman 
![ddrillini-chan](https://user-images.githubusercontent.com/1487413/44564324-fcb3b900-a727-11e8-8a8c-128c3e059b24.png)
![steps](https://user-images.githubusercontent.com/1487413/44564325-fcb3b900-a727-11e8-8d0f-08dd4651d442.png)

@ianklatzco:
![ddrillini-logo-attempt](https://user-images.githubusercontent.com/1487413/44564430-7cda1e80-a728-11e8-8b4c-5454c1076151.png)

@benpai
![wendys_club](https://user-images.githubusercontent.com/1487413/44564428-7a77c480-a728-11e8-9ba7-ebed0fa1560b.png)

**Comment by ianklatzco** [comment]
I like @impman's steps a lot. They're nicely vectorized and will be really easily to turn into clothes / other things.

Eventually I want to get a marquee and replace this screen with the logo.

<img width="1392" alt="screenshot 2018-08-23 22 40 03" src="https://user-images.githubusercontent.com/1487413/44564472-ab57f980-a728-11e8-88bf-a6fe26bfaee9.png">

**Comment by impman** [comment]
Oh you forgot this one too
colors can of course be changed anytime
![ddrillini logo](https://user-images.githubusercontent.com/6895211/44615269-ebd47780-a7fb-11e8-8fe4-1c948d874678.png)

**Comment by ianklatzco** [comment]
(nice)

**Comment by ianklatzco** [comment]
wouldn't vectorize well which would suck

![image](https://user-images.githubusercontent.com/1487413/45810971-8dcb7080-bc91-11e8-9719-3e917d051b51.png)

**Comment by ianklatzco** [comment]
here's cabby (penn state)
![cabby](https://user-images.githubusercontent.com/1487413/46240340-85e38e80-c36b-11e8-94da-82baa1c8545f.jpg)

**Comment by ianklatzco** [comment]
thanks to dan c:
![psu-marquee](https://user-images.githubusercontent.com/1487413/46249426-bfa9a900-c3ee-11e8-98e2-5a89e2b753a8.png)

**Comment by ianklatzco** [comment]
oscar made a new logo, which we will be turning into a new marquee at the end of the year.

**Comment by ianklatzco** [comment]
dee-chan images stored in https://drive.google.com/open?id=1KGSgqqV4W8HwE4_wniMqeIy5THmYTuWT

which is `gdrive/branding/fanart`
