### ISSUE TITLE
mines don't stop tweening

### ISSUE THREAD

**Issue by ianklatzco** [ddrillini/uiuc-wendy#7]
this is an upstream bug somewhere. i don't really care to fix it because i don't think it's much of a problem.

when a mine is hit, the animation plays for longer than it should.
![gif](https://user-images.githubusercontent.com/1487413/35140481-04e60472-fcbd-11e7-9b6c-960a60661880.gif)

mute told me that the fix is to modify each noteskin, adding a line of text to the noteskin's `metrics.ini`.

this solution sucks. it requires modifying every noteskin.

idk if the bug's been fixed in upstream (stepmania), but if someone wants to dig into stepmania code for the first time, this is a good place to start.

<img width="347" alt="mine-explosions" src="https://user-images.githubusercontent.com/1487413/35140343-83946a3a-fcbc-11e7-8a51-ba739af7099b.png">

**Comment by ianklatzco** [comment]
ask @mutesauce for details.

**Comment by andrewipark** [comment]
Noteskin metrics on the cab are a complete and utter mess. Further, there are at least 2 or 3 different versions of metrics floating around on the internet.

This will take a lot of pain to consolidate and fix.

**Comment by mutesauce** [comment]
If it's at all helpful, I have a bundle of SM5.0.12 noteskins that all have the mine tweening fix. Included are cel, metal, robot, enlightenment, vel, and scaleable (as well as their variants for ECFA and Stomperz/Rhythm Horizon modes). http://www.r21freak.com/mute/simfiles/themes/SM5-NoteSkins-mute.zip

**Comment by ianklatzco** [comment]
sweet, thank you much. andrew, let's replace the ones we have on there w/ ithese.

**Comment by andrewipark** [comment]
looks like some of those use scalable hit splashes
Still working on this, will probably be a while

**Comment by andrewipark** [comment]
This will be fixed alongside #54
