### ISSUE TITLE
upload crowdpleasers

### ISSUE THREAD

**Issue by ianklatzco** [ddrillini/uiuc-wendy#70]
https://www.dropbox.com/sh/kzlieoq2o2kr51e/AADR7DcdPFjtuBqX5KmWlgu4a?dl=0

https://www.dropbox.com/sh/aowmtai4f6trv7g/AAC2LssWNMh0GsLsyo1pE5N9a?dl=0

**Comment by andrewipark** [comment]
Is this ok to close? i thought i saw this on the machine now.
