### ISSUE TITLE
consolidate "scripts" and "util"

### ISSUE THREAD

**Issue by andrewipark** [ddrillini/uiuc-wendy#72]
I'm not entirely sure what the difference is.

**Comment by ianklatzco** [comment]
util is a folder on the machine, containing swap scripts.

scripts is random stuff that's generally not used except for sendsimfiles.

**Comment by ianklatzco** [comment]
i literally `scp -r itg:util ~/ddrillini/uiuc-wendy`'d

imo: drop a readme saying as much in both dirs

**Comment by ianklatzco** [comment]
0691f13378ed8999b336986a0d8fe915798c44a0

**Comment by ianklatzco** [comment]
i think that's probably best solution. alternative is clone this repo to machine (maybe just `rsync` updates all the time?

**Comment by ianklatzco** [comment]
see comment in commit about needing to keep it up to date

**Comment by andrewipark** [comment]
maybe util should be machine-side stuff, scripts is client-side...

**Comment by ianklatzco** [comment]
imo they should stay separate.
