### ISSUE TITLE
replace rip10.5 with this

### ISSUE THREAD

**Issue by ianklatzco** [ddrillini/uiuc-wendy#79]
this version has no difficult prefixes
~~https://drive.google.com/open?id=1k6SuZc5ClQAP1ma9eKpnw2oNEHc90eWi~~

**Comment by ianklatzco** [comment]
udptaed https://drive.google.com/open?id=1z583lxxjUR7LZ1niUMcr8vy_0VFpojO4

**Comment by andrewipark** [comment]
did this today
