### ISSUE TITLE
pull PIUIO out of old PC and power it with something else (new pc power supply? USB to molex 4 pin?{

### ISSUE THREAD

**Issue by ianklatzco** [ddrillini/uiuc-wendy#81]

**Comment by andrewipark** [comment]
are we just gonna straight up toss the old ITG PC after that, then

**Comment by ianklatzco** [comment]
it'll live behind the machine b/c it belongs to melody.

**Comment by ianklatzco** [comment]
i bought the right part but apparently we need two.

todo:
* check to see if the PSU on that computer has molex.

**Comment by andrewipark** [comment]
was this ever fixed?

**Comment by ianklatzco** [comment]
yes
