### ISSUE TITLE
Mod charts

### ISSUE THREAD

**Issue by sangyeolbaek** [ddrillini/uiuc-wendy#88]
Mod charts like botanic panic (not the ones in Mods folder) do not work properly

**Comment by ianklatzco** [comment]
can you provide a list of mods charts please?

**Comment by andrewipark** [comment]
Note to self: check perms on `Preferences.ini`. Other events made it clear that the mute actions pref wasn’t being saved properly, either.

This might require a full cache rebuild.

**Comment by sangyeolbaek** [comment]
from what I know:

botanic panic
hopes and dreams (Undertale)

**Comment by ianklatzco** [comment]
Can you describe how they fail?
