### ISSUE TITLE
P1 Front panel control buttons sticking

### ISSUE THREAD

**Issue by andrewipark** [ddrillini/uiuc-wendy#89]
This is particularly bad for P1 right, but left has been sticking too. Can we get melody to fix the mech?

**Comment by ianklatzco** [comment]
please go tell donna. ask her to ask them if they have spare front panel buttons, and email her a picture of them. also send donna a link for where to order them.

**Comment by impman** [comment]
If you can access the back of the front panel, they should just unscrew, then you can scrub the button internals with a toothbrush to get out the accumulated sweat and grime that's probably causing the sticking.

**Comment by ianklatzco** [comment]
@impman feel free to give it a shot. I'm happy to help, some time when we're both there.

**Comment by andrewipark** [comment]
haven't noticed this in a while, surprisingly.
