### ISSUE TITLE
Break songs from courses should not be selectable on music wheel

### ISSUE THREAD

**Issue by andrewipark** [ddrillini/uiuc-wendy#9]
like "break (1min)" etc
I think you can do this with a flag in the SM file.

**Comment by andrewipark** [comment]
I modified the flags in the SM file, but they still show up on MusicWheel. This might be a different SM setting or something in SL5 or some such.

**Comment by andrewipark** [comment]
Closing. If we turn the SM option to get rid of "special" songs on the song wheel on, then this necessitates checking 10,000 `#SELECTABLE` tags.

**Comment by ianklatzco** [comment]
that can't be too hard (grep for `SELECTABLE`) but it requires checking every new simfile on the machine so i think it should be off.
