### ISSUE TITLE
negotiate credit sharing agreement with donna

### ISSUE THREAD

**Issue by ianklatzco** [ddrillini/uiuc-wendy#91]
i will handle this in spring semester.

**Comment by andrewipark** [comment]
there's like 7 or 8 weeks left in the semester

**Comment by andrewipark** [comment]
Probably not happening now.

**Comment by ianklatzco** [comment]
Still possible -- Shane might buy the cab.

**Comment by ianklatzco** [comment]
Remind Frank about it and ask him to call J&J to float the idea.
