### ISSUE TITLE
write lua that forces no cmod

### ISSUE THREAD

**Issue by ianklatzco** [ddrillini/uiuc-wendy#97]
summary:
* mod our version of simply love to check if the title or subtitle of the song contains no cmod
* if a player selected cmod, automatically convert it to a mmod

---

![image](https://user-images.githubusercontent.com/1487413/51870452-4a58d100-2319-11e9-90a3-2516fd2050cb.png)
![image](https://user-images.githubusercontent.com/1487413/51870468-55136600-2319-11e9-8f40-ec30fc9e377d.png)

**Comment by ianklatzco** [comment]
https://github.com/nayotodot/StepMania-Mods-Template/blob/master/5.0/background/mods.lua?fbclid=IwAR0ZQb25NkOxUJDCo0AEFE4_hflXyqi0ldl90IBJ8WEE72fnwStqt7DmeiY#L103-L116

**Comment by andrewipark** [comment]
closing b/c active PR

**Comment by ianklatzco** [comment]
in most standard github interactions i’ve seen on other projects, you tie the issue to the PR by mentioning the issue number in the PR. then, when you merge the PR, it usually auto closes the issue (regex match)

**Comment by ianklatzco** [comment]
see https://github.com/ddrillini/Simply-Love-SM5/pull/10
https://github.com/ddrillini/Simply-Love-SM5/pull/30
