### ISSUE TITLE
coindata parsing for donna

### ISSUE THREAD

**Issue by ianklatzco** [ddrillini/uiuc-wendy#98]
timeline:
* 2017ish march or before sm5pc installed (probably in the fall)
* TODO GET: coins.xml from mattpc from may-2018
* `14-feb-2018-coins.xml`
* sp2018 (may-ish) we swap mattpc for ianpc. 
* `15-nov-2018-coins.xml`
* TODO GET: new coins.xml

OR just compare august-december 2017 from 14-feb-2018 off a new coindata

**Comment by ianklatzco** [comment]
```
ok so here's the deal
we grab a new coins.xml off the machine
it gives us august-december of 2018
14-feb-2018-coins.xml should contain august-december of 2017
we get weekly usage data for both years
graph it
and graph percent increase
send this to donna
```

@trevorm4 will grab it off the machine & handle data processing

**Comment by ianklatzco** [comment]
`find / -name 'Coins.xml' 2>/dev/null
```
(in any case it's probably ~/.stepmania-5.1/Data/Coins.xml)
there's probably two copies
a sm5.0 and a sm5.1
you might need to do some stitching together of the data
```

**Comment by trevorm4** [comment]
Here's the coin data from the machine

[Coins.zip](https://github.com/ddrillini/uiuc-wendy/files/2820527/Coins.zip)

Will do coin stuff next week most likely

**Comment by ianklatzco** [comment]
thank youuuuuu

>
